spring.application.name=api-gateway
server.port=${SERVER_PORT}
# --- Route Definitions ---
#user
spring.cloud.gateway.server.webflux.routes[0].id=user-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=${USER_SERVICE_URI}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**
#product
spring.cloud.gateway.server.webflux.routes[1].id=product-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=${PRODUCT_SERVICE_URI}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/products/**


logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG