spring.application.name=api-gateway
server.port=${SERVER_PORT}

# Register gateway in Eureka & discover services
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Enable the gateway to use Eureka for routing
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# --- Route Definitions ---
#user
spring.cloud.gateway.server.webflux.routes[0].id=user-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=${USER_SERVICE_URI}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**
#product
spring.cloud.gateway.server.webflux.routes[1].id=product-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=${PRODUCT_SERVICE_URI}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/products/**

management.endpoints.web.exposure.include=health,info