spring.application.name=user-service

# Server Port
server.port=${SERVER_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update

# JWT Secret Key
app.jwt.secret=${JWT_SECRET_KEY}
