spring.application.name=discovery-server
server.port=8761

# Eureka server should NOT register to itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost

management.endpoints.web.exposure.include=health,info




